### PR TITLE
workon: start shell using exec instead of subprocess.check_call.

### PR DESCRIPTION
**Pull request by etoombs-encircle**
For one thing, this is a good idea anyway, since there is no reason to keep running python after the shell has started.

For another thing, there are some shells like fish that somewhat expect this. If you don't start fish with an exec, it can't receive ^Cs, and if you type one, the whole shell just exits. So, that's not good.

### CODE REVIEW

**Comment by rraval** [comment]
No issues with the code, did you try with `bash` / `zsh` besides just `fish` and make sure this doesn't break anything there?

**Comment by etoombs-encircle** [comment]
Not sure how, lol. I try starting pew from zsh and it starts fish. I think it's reading /etc/passwd to get the user's default shell. Let me try changing it.

**Comment by etoombs-encircle** [comment]
oh, it was reading $SHELL, which for some reason didn't change when I started zsh... anyway, I tested with bash and zsh. Success.

**Comment by rraval** [comment]
Can you rebase this onto the `ini` branch. That's the one that contains the `.inve.ini` parsing stuff.

**Comment by rraval** [comment]
FWIW, I'm hoping to kill this `pew` fork eventually and move to something that parses `.env` files, but I need to find time for that first.

**Comment by etoombs-encircle** [comment]
I knew you were going to kill this thing, but meanwhile, the ^C thing was getting really annoying and I knew it would be easy to fix. OK, I'm trying the rebase now.

**Comment by etoombs-encircle** [comment]
OK, I just rebased.

**Pull request merged**
